# Generated by Django 4.0.5 on 2022-06-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securetea_api', '0002_remove_user_id_user_loggedin_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='loggedin',
        ),
    ]
